// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: apartment_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ApartmentService_Get_FullMethodName = "/ApartmentService/Get"
)

// ApartmentServiceClient is the client API for ApartmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApartmentServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type apartmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApartmentServiceClient(cc grpc.ClientConnInterface) ApartmentServiceClient {
	return &apartmentServiceClient{cc}
}

func (c *apartmentServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, ApartmentService_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApartmentServiceServer is the server API for ApartmentService service.
// All implementations must embed UnimplementedApartmentServiceServer
// for forward compatibility
type ApartmentServiceServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedApartmentServiceServer()
}

// UnimplementedApartmentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedApartmentServiceServer struct {
}

func (UnimplementedApartmentServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedApartmentServiceServer) mustEmbedUnimplementedApartmentServiceServer() {}

// UnsafeApartmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApartmentServiceServer will
// result in compilation errors.
type UnsafeApartmentServiceServer interface {
	mustEmbedUnimplementedApartmentServiceServer()
}

func RegisterApartmentServiceServer(s grpc.ServiceRegistrar, srv ApartmentServiceServer) {
	s.RegisterService(&ApartmentService_ServiceDesc, srv)
}

func _ApartmentService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApartmentServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApartmentService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApartmentServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApartmentService_ServiceDesc is the grpc.ServiceDesc for ApartmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApartmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ApartmentService",
	HandlerType: (*ApartmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ApartmentService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apartment_service.proto",
}
